// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "Chat API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/m0a-mystudy/goa-chat/design
// --out=$(GOPATH)/src/github.com/m0a-mystudy/goa-chat
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// RoomHref returns the resource href.
func RoomHref(roomID interface{}) string {
	paramroomID := strings.TrimLeftFunc(fmt.Sprintf("%v", roomID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/rooms/%v", paramroomID)
}
