// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "Chat API": serve TestHelpers
//
// Command:
// $ goagen
// --design=github.com/m0a-mystudy/goa-chat/design
// --out=$(GOPATH)/src/github.com/m0a-mystudy/goa-chat
// --version=v1.2.0-dirty

package test
