// Package models contains the types for schema 'goa_chat'.
package models

// GENERATED BY XO. DO NOT EDIT.

import (
	"time"
)

// MessagesWithAccount represents a row from 'goa_chat.messages_with_account'.
type MessagesWithAccount struct {
	ID           int       `json:"id"`             // id
	RoomID       int       `json:"room_id"`        // room_id
	Body         string    `json:"body"`           // body
	Postdate     time.Time `json:"postDate"`       // postDate
	Name         string    `json:"name"`           // name
	Email        string    `json:"email"`          // email
	GoogleUserID string    `json:"google_user_id"` // google_user_id
	Image        []byte    `json:"image"`          // image
}
