// Package models contains the types for schema 'goa_chat'.
package models

// GENERATED BY XO. DO NOT EDIT.

// NewMessage calls the stored procedure 'goa_chat.new_message(int(11), int(11), varchar(400)) int(11)' on db.
func NewMessage(db XODB, v0 int, v1 int, v2 string) (int, error) {
	var err error

	// sql query
	const sqlstr = `SELECT goa_chat.new_message(?, ?, ?)`

	// run query
	var ret int
	XOLog(sqlstr, v0, v1, v2)
	err = db.QueryRow(sqlstr, v0, v1, v2).Scan(&ret)
	if err != nil {
		return 0, err
	}

	return ret, nil
}
